# Generated by Django 3.1.5 on 2021-04-02 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('role', models.CharField(blank=True, choices=[('Web Developer', 'Web Developer'), ('Software Engineer', 'Software Engineer'), ('Software Tester', 'Software Tester'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Developer', 'UI/UX Developer'), ('Team Leader', 'Team Leader'), ('IOS Developer', 'IOS Developer'), ('Android Developer', 'Android Developer')], default='None', max_length=50, null=True)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='None', max_length=5, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('total_ctc', models.FloatField()),
                ('joining_date', models.DateField(default=datetime.date(2021, 4, 2))),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', models.FloatField()),
                ('basic', models.FloatField()),
                ('DA', models.FloatField()),
                ('HRA', models.FloatField()),
                ('Conveyance', models.FloatField()),
                ('Allowance', models.FloatField()),
                ('Medical_Allowance', models.FloatField()),
                ('other_earnings', models.FloatField()),
                ('TDS', models.FloatField()),
                ('ESI', models.FloatField()),
                ('PF', models.FloatField()),
                ('Leave', models.FloatField()),
                ('Prof_Tax', models.FloatField()),
                ('Labour_Welfare', models.FloatField()),
                ('other_deductions', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
    ]
