# Generated by Django 3.1.5 on 2021-04-05 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salary_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.date(2021, 4, 5)),
        ),
    ]
